### ISSUE TITLE
Cannot compile library under MonoDevelop

### ISSUE THREAD

**Issue by brenttaft** [jenyayel/SignalR.Client.20#2]
I am trying to compile the SignalR library with the version of MonoDevelop that is included with Unity.  However, I am receiving the following compile errors:

Error CS0433: The imported type `System.Action' is defined multiple times (CS0433) (SignalR.Client.20)
Error CS0433: The imported type`System.Func<TResult>' is defined multiple times (CS0433) (SignalR.Client.20)

Another question is - will this work on IOS and Android?

Thanks,
Brent

**Comment by bakman23** [comment]
That's works on IOS 9 haven't test on others! 
Great job!!!!

**Comment by jenyayel** [comment]
Thanks.
