### ISSUE TITLE
await + invoke

### ISSUE THREAD

**Issue by samansadeghpour** [jenyayel/SignalR.Client.20#4]
Hi, tanx for ur dll :)
I want call a method from server that return a json o string value, but from this article : 
"http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-net-client",
in section : "Client code calling a method that has a return value and takes a complex type parameter, in an ASP.NET 4.5 async method",
I can't use ur dll like this!
Is there any way for use this code or another way to get reternet data from server?

Best regards.

**Comment by jenyayel** [comment]
This is similar to:
```cs
stockTickerHub
    .Invoke<IEnumerable<Stock>>("AddStock", new Stock() { Symbol = "MSFT" })
    .Finished += (object sender, CustomEventArgs<IEnumerable<Stock>> e) =>
    {
        foreach (Stock stock in e.Result)
        {
            textBox.Text += string.Format("Symbol: {0} price: {1}\n", stock.Symbol, stock.Price);
        }
    };
```

**Comment by samansadeghpour** [comment]
It's serever method:

<pre>public string SayHi(string test)
 {
 return "Hi Baby!";
 }</pre>

And in unity:

<pre>
_hubProxy.Invoke<string> ("SayHi").Finished +=
 (object sender, CustomEventArgs<string> e) =>
 {
 print(e.Result); //Returns null
 };
</pre>

But it returns NULL!!

**Comment by jenyayel** [comment]
I'm not sure what you are trying to do. It seems that you are doing the "usual" request-reply. Why? Anyway, the same functionality is achiveid by subscribing to specific event and then invoking it

In your Unity:

```cs
HubConnection _conn = new HubConnection("http://YOUR SERVER/");
IHubProxy _proxy = _conn.CreateProxy("TestHub");

// subscribe to event
_proxy.Subscribe("SayHi").Data += data =>
{
    if (data == null || data.Length == 0)
        return;

    JToken _first = data[0] as JToken;
    print(_first["message"].ToString());
};

// open connection to server
_conn.Start();

// invoke command
_proxy.Invoke("SayHi");
```

In your server hub:

```cs
public class TestHub : Hub
{
    public void SayHi()
    {
        // not that here we sending a message only to the client
        // who invoke this method (Context.ConnectionId)
        Clients
            .Client(Context.ConnectionId)
            .SayHi(new { message = "Hi there!" } );
    }
}
```

**Comment by jenyayel** [comment]
I also updated demo, so it contains working example of both - server and client.

**Comment by samansadeghpour** [comment]
Actualy I want to call some method in client from server and prosses the resault together, In othre words I want a duplex method to request to server and then get the resault from it but not from Subscribe!

**Comment by jenyayel** [comment]
OK, I fixed this, see 766f81a2abfcfd0cb1bda91f7088e7f26358cf62. The result wasn't de-serialized. I added more examples too.

**Comment by samansadeghpour** [comment]
Tanx buddy, It works nice.

**Comment by jenyayel** [comment]
I'm glad it helped you.
