### ISSUE TITLE
How to specify query string parameters

### ISSUE THREAD

**Issue by mberneti** [jenyayel/SignalR.Client.20#5]
I want to send data to the server when the client connects , like this :
[ASP.NET SignalR Hubs API Guide - .NET Client (C#)](http://www.asp.net/signalr/overview/guide-to-the-api/hubs-api-guide-net-client#querystring)
```
// .NET Client
var querystringData = new Dictionary<string, string>();
querystringData.Add("contosochatversion", "1.0");
var connection = new HubConnection("http://contoso.com/", querystringData);
```
or like this :
```
// javascript client
$.connection.hub.qs = "myInfo=12345";
```
how implement this in SignalR.Client.20?

**Comment by jenyayel** [comment]
Added relevant constructor to HubConnection 95249856025f2cc338ce7adbf3a2a7029407fe29. Same usage as in native client.

**Comment by mberneti** [comment]
thank you.

**Comment by jenyayel** [comment]
You are welcome.

**Comment by scarffy** [comment]
Hi,

Sorry to revive the old thread.

If I want to do like this:

`_hubconnection = new HubConnection(url, "Authorization={token}");`

is it the same as suggested solution?

**Comment by jenyayel** [comment]
Should be, as far as I remember. There is an [example in demo](https://github.com/jenyayel/SignalR.Client.20/blob/95249856025f2cc338ce7adbf3a2a7029407fe29/source/Demo/ClientDemo/Program.cs#L22).

**Comment by scarffy** [comment]
Sorry I'm a bit of noob here. In the example, 

I need to create a new dictionary and pass 2 parameter inside right?
Can I pass only one parameter or there is no way I can do that?

Thank you in advance

**Comment by jenyayel** [comment]
That's fine. The dictionary in this case is a collection of all parameters that goes into query string. So, for instance, if you want to create this such URI `http://localhost?key=blabla`, then you need to create the following structure:
```
var query = new Dictionary<string, string>();
query.Add("key", "blabla");
``` 
Makes sense?

**Comment by scarffy** [comment]
Oh! I think I understand when you mention `http://localhost?key=blabla` part.

So in my case, I want to pass the Authorization key and token.
I should do like this right?

```
var query = new Dictionary<string, string>();
query.Add("Authorization", token);
_hubconnection = new HubConnection(url, query);
```
