### ISSUE TITLE
Does the SignalR.Client.20 support iOS?

### ISSUE THREAD

**Issue by akira32** [jenyayel/SignalR.Client.20#6]
Does the SignalR.Client.20 support iOS?
I am sure it support Android by the persistence connection. But the persistence connection does not work on iPad mini. Should I try the hub connection?

**Comment by jenyayel** [comment]
The library intended for .NET 2.0 and [Mono](http://www.mono-project.com/). So basicly, the library should work fine on every platfrom supported by those two.

**Comment by akira32** [comment]
My SignalRServer should downgrade from 4.0 to 2.0 net?

**Comment by jenyayel** [comment]
Absolutely not. The primary reason for this project is to have SignalR **client** that able to run in .NET 2.0.

**Comment by akira32** [comment]
In Unity's Plugins directory, I put the Newtonsoft.Json.7.0.1\lib\net20\Newtonsoft.Json.dll. I also put your SignalR.Client.20 directory in Unity's Scripts directory. Should I compile your SignalR.Client.20 to a dll and then put into Unity's Plugins directory?

**Comment by akira32** [comment]
Hello! jenyayel ! Could you put your Unity Project to GitHub? I think that maybe the setting problem or dll problem. Thanks!

**Comment by jenyayel** [comment]
Sorry for the late response. I don't have such thing, but it should be pretty much straight forward - you should compile and place it in your plugins directory.
