### ISSUE TITLE
connection.start() hangs Unity IDE if no Internet (even when connecting to localhost)

### ISSUE THREAD

**Issue by DannyT** [jenyayel/SignalR.Client.20#7]
Whilst working on the train the other day without a web connection. I noticed the Unity IDE hangs when calling connection.start() even if the connection is supposedly going to a local URL.

Literally the following script on an empty GameObject kills Unity if I switch my wifi off but works fine with it on:

```
using UnityEngine;
using SignalR.Client._20;
using SignalR.Client._20.Hubs;
using System;

public class SocketController : MonoBehaviour {
    void Start () {
        connection = new HubConnection(''http://localhost:12345');
        proxy = connection.CreateProxy("MyHub");
        connection.Start();
    }
}
```

**Comment by jenyayel** [comment]
Strange. I'm able to start connection to hub without active Internet connection. May be it is something related to IDE? Which one do you use?

Out of cariousity, why do you still use this client?

**Comment by MrTortoise** [comment]
why wouldn't he use this client?

**Comment by jenyayel** [comment]
> why wouldn't he use this client?

It is outdated and uses old and very specific version of SignalR's protocol.

**Comment by MrTortoise** [comment]
Ok,  so what would you do now? I'm a bit of a noob here.  Websocketsharp seems the alternative but wondering what you might suggest. 
Thanks

**Comment by jenyayel** [comment]
I'm not developing in Unity for a few years, so I'm not an expert. The main idea behind me developing this library was that Mono didn't support the version of .NET that required by SignalR client library back then. It is now. Besides, there are other options (like the one you mentioned), or ` Owin WebSocket Extensions` and also a new version of SignalR that it is being cooked now.

**Comment by DannyT** [comment]
Sorry, did not get notified of replies! This is happening in the Unity 5.4 IDE (just tested and getting same error in 5.5). I'm a total Unity noob so was under the impression I needed to use something that supported .Net 2.0. Is this not the case?

I've got the connection.start() method wrapped in a try/catch is there perhaps an .on error event I should be handling instead?

**Comment by jenyayel** [comment]
If you bounded to .NET 2.0, then yes, probably this is the best option for you. Can you check with Fiddler or Wireshark what type of traffic and where to heading when IDE hangs?

**Comment by NDark** [comment]
Hi all, just happen to found this library and I have similar question.

I established a server on my windows by using damienbod/SignalRHostWithUnity.

Then I tried this library in Unity on Standalone(Windows and Mac), Android. They all succeed in communicating with this local server (with a LAN ip and port).
But when I tried to deploy on iOS (iPad) device in the same LAN, it hangs when connection.Start().

My setting of Unity iOS are Scripting Backend: IL2CPP, API Commatibility level: .NET 2.0 (not subset)

Do I need to open or modify some sort of network privilege or setting? Or do I miss anything iOS library?

(update)

I solve my problem by using another library deriving from here: https://github.com/gromchen/uSignalR , but I need to use a modified version newton json library: https://github.com/SaladLab/Json.Net.Unity3D . A heavily combined solution but at least works. Thanks anyway.

**Comment by keraj37** [comment]
I had similar issue lately, but I just use WebSockets now.

I will try [https://github.com/gromchen/uSignalR](https://github.com/gromchen/uSignalR) though. Thanks **NDark**!

**Comment by jenyayel** [comment]
I think it worth waiting for the release of the new completly rewritten [SignalR](https://github.com/aspnet/signalr), which solves all issues that we had with the old one and the reason why this repo exists. BTW, you don't have to wait you can start playing with pre-release, I bet it much stable than this repo or other forks people pointed out here.
